<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class COMPRAS_ITENS extends Model
{
    use HasFactory;
    protected $connection;
    function __construct()
    {
        return $this->connection = env('APP_NAME');
    }
	protected $table = 'COMPRAS_ITENS';
    protected $primaryKey = ['CMP_NUMERO','CMI_ITEM'];
    public $timestamps = false;

    protected $fillable= [
        'CMP_NUMERO'
        ,' CMI_ITEM'
        ,' PRD_CODIGO'
        ,' PRD_CODIGO_DIGITADO'
        ,' NCM_CODIGO'
        ,' CMI_UM_COMPRA'
        ,' CMI_FATOR_CONF'
        ,' CMI_QTDE_ENTRADA_ESTOQUE'
        ,' CMI_QTDE'
        ,' CMI_VL_UNIT'
        ,' CMI_VL_UNIT_BRUTO'
        ,' CMI_VL_CUSTO_AQUISICAO'
        ,' CMI_PERC_DESCONTO'
        ,' CMI_VALOR_DESCONTO'
        ,' CMI_VL_TOTAL'
        ,' CFOP_CODIGO_NF_ORIGINAL'
        ,' CFOP_CODIGO_NF'
        ,' CFOP_CODIGO'
        ,' CMI_ICMS_ORIGEM_MERCADORIA'
        ,' CST_ICMS'
        ,' CMI_VL_BASE_CALCULO_ICMS'
        ,' CMI_AL_ICMS_REDUCAO'
        ,' CMI_AL_ICMS'
        ,' CMI_VL_ICMS'
        ,' CMI_CSOSN'
        ,' CMI_BC_CREDITO_SIMPLES'
        ,' CMI_AL_CREDITO_SIMPLES'
        ,' CMI_VL_CREDITO_SIMPLES'
        ,' CMI_MVA_ICMS_ST'
        ,' CMI_RED_BASE_CALCULO_ICMS_ST'
        ,' CMI_VL_BASE_CALCULO_ICMS_ST'
        ,' CMI_AL_ICMS_ST'
        ,' CMI_VL_ICMS_ST'
        ,' CST_IPI'
        ,' CMI_VL_BASE_CALCULO_IPI'
        ,' CMI_AL_IPI'
        ,' CMI_VL_IPI'
        ,' CST_PIS'
        ,' CMI_VL_BASE_CALCULO_PIS'
        ,' CMI_VL_PIS'
        ,' CST_COFINS'
        ,' CMI_VL_BASE_CALCULO_COFINS'
        ,' CMI_VL_COFINS'
        ,' CMI_VL_FRETE'
        ,' CMI_VL_SEGURO'
        ,' CMI_VL_OUTRAS_DESPESAS'
        ,' CMI_CONFIRMADO'
        ,' CMI_CREDITO_IMPOSTOS'
        ,' CMI_VL_PRECO_VENDA_ANT'
        ,' CMI_VL_PRECO_MINIMO_ANT'
        ,' CMI_VL_PRECO_VENDA_SUGERIDO_ANT'
        ,' CMI_FPV_CODIGO'
        ,' CMI_VL_PRECO_VENDA_SUGERIDO'
        ,' CMI_VL_PRECO_VENDA_MIN_SUGERIDO'
        ,' CMI_ATUALIZAR_PRECO_CADASTRO'
        ,' CMI_VL_PRECO_VENDA_DIGITADO'
        ,' CMI_VL_PRECO_VENDA_MIN_DIGITADO'
        ,' CMI_VL_TOTAL_COM_DESCONTO'
        ,' CMI_PERC_DIRETO_SOBRE_CUSTO'
        ,' CMI_VL_CUSTO_MANUAL'
        ,' CST_S_ICMS'
        ,' CMI_S_VL_BASE_CALCULO_ICMS'
        ,' CMI_S_AL_ICMS_REDUCAO'
        ,' CMI_S_AL_ICMS'
        ,' CMI_S_VL_ICMS'
        ,' CMI_S_MVA_ICMS_ST'
        ,' CMI_S_RED_BASE_CALCULO_ICMS_ST'
        ,' CMI_S_VL_BASE_CALCULO_ICMS_ST'
        ,' CMI_S_AL_ICMS_ST'
        ,' CMI_S_VL_ICMS_ST'
        ,' CST_S_IPI'
        ,' CMI_S_VL_BASE_CALCULO_IPI'
        ,' CMI_S_AL_IPI'
        ,' CMI_S_VL_IPI'
        ,' CST_S_PIS'
        ,' CMI_S_VL_BASE_CALCULO_PIS'
        ,' CMI_S_VL_PIS'
        ,' CST_S_COFINS'
        ,' CMI_S_VL_BASE_CALCULO_COFINS'
        ,' CMI_S_VL_COFINS'
        ,' CMI_AL_PIS'
        ,' CMI_AL_COFINS'
        ,' CMI_S_AL_PIS'
        ,' CMI_S_AL_COFINS'
        ,' CMI_ARREDONDAMENTO_TRUNCAMENTO'
        ,' CMI_VL_RATEIO_DOC_ARRECADACAO'
        ,' CMI_VL_RATEIO_DOC_REFERENCIADO'
        ,' CMI_XML_PRODUTO_DESCRICAO'
        ,' CMI_XML_CODIGO_BARRAS_COM'
        ,' CMI_XML_CODIGO_BARRAS_TRIB'
        ,' CMI_XML_UNIDADE_MEDIDA_COM'
        ,' CMI_XML_UNIDADE_MEDIDA_TRIB'
        ,' CMI_VL_CUSTO_AQUISICAO_DESPESAS'
        ,' CMI_QTDE_ETIQUETAS'
        ,' CMI_CREDITO_ULTIMA_COMPRA'
        ,' CMI_BC_ICMS_ST_RETIDO'
        ,' CMI_VL_ICMS_ST_RETIDO'
        ,' CMI_VL_FRETE_RATEIO'
        ,' CMI_VL_SEGURO_RATEIO'
        ,' CMI_VL_OUTRAS_DESPESAS_RATEIO'
        ,' CMI_FCI'
        ,' USU_CODIGO_VENDA'
        ,' CEST_CODIGO'
        ,' CMI_INFORMACAO_ADICIONAL'
        ,' CMI_XPED'
        ,' CMI_NITEMPED'
        ,' CMI_IND_ESCALA'
        ,' CMI_IND_ESCALA_CNPJ_FAB'
        ,' CMI_C_BENEF'
        ,' CMI_P_FCPSTRET'
        ,' CMI_MARGEM_BRUTA_PERCENTUAL'
        ,' CMI_AL_ICMS_ST_RETIDO'
        ,' CMI_AL_FCPST'
        ,' CMI_ICMS_SUBSTITUIDO'
        ,' CMI_PROCESSADO_GRADE'
        ,' LOT_NUMERO'
        ,' PROD_ANP_COD'
    ];

}
