<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class COMPRAS extends Model
{
    use HasFactory;
    protected $connection;
    function __construct()
    {
        return $this->connection = env('APP_NAME');
    }
	protected $table = 'COMPRAS';
    protected $primaryKey = 'DOC_NUMERO';
    public $timestamps = false;

    protected $fillable= [
        'CMP_NUMERO'
        ,' ORD_NUMERO'
        ,' CMP_DT_INCLUSAO'
        ,' CMP_DOC_DT_EMISSAO'
        ,' CMP_DT_ENTRADA'
        ,' CMP_DOC_DOCUMENTO'
        ,' CMP_DOC_VL_FRETE'
        ,' CMP_DOC_VL_PRODUTOS'
        ,' CMP_DOC_VL_OUT_DESPESAS'
        ,' CMP_DOC_VL_TOTAL'
        ,' CMP_OBSERVACOES'
        ,' USU_COD'
        ,' CPA_CODIGO'
        ,' ENT_CODIGO'
        ,' CMP_SITUACAO'
        ,' CMP_DT_CANCELAMENTO'
        ,' CMP_USU_COD_CANCELAMENTO'
        ,' CMP_DT_CONFIRMACAO'
        ,' CMP_USU_COD_CONFIRMACAO'
        ,' CMP_DOC_VL_DESCONTO'
        ,' CMP_DOC_VL_CREDITO_IMPOSTOS'
        ,' CMP_DOC_VL_FRETE_ICMS'
        ,' TRA_CODIGO'
        ,' CMP_FRETE_CONHECIMENTO_NUMERO'
        ,' CMP_FRETE_CONHECIMENTO_VALOR'
        ,' CMP_FRETE_CONHECIMENTO_VENCTO'
        ,' CMP_CNPJ_DIGITADO'
        ,' CMP_VL_BASE_CALC_ICMS'
        ,' CMP_VL_ICMS'
        ,' CMP_VL_BASE_CALC_ICMS_SUBST'
        ,' CMP_VL_ICMS_SUBST'
        ,' CMP_VL_SEGURO'
        ,' CMP_VL_IPI'
        ,' CMP_VL_PIS'
        ,' CMP_VL_COFINS'
        ,' CMP_TOTALIZACAO_MANUAL'
        ,' CMP_MODELO'
        ,' CMP_TIPO_FRETE'
        ,' CMP_VL_PIS_ST'
        ,' CMP_VL_COFINS_ST'
        ,' NFE_CHAVE'
        ,' CMP_CARGA_VOLUMES'
        ,' CMP_CARGA_ESPECIE'
        ,' CMP_CARGA_MARCA'
        ,' CMP_CARGA_NUMERO'
        ,' CMP_CARGA_PESO_BRUTO'
        ,' CMP_CARGA_PESO_LIQUIDO'
        ,' CMP_VEICULO_UF'
        ,' CMP_VEICULO_PLACA'
        ,' NS_SERIE'
        ,' NS_SUB_SERIE'
        ,' CMP_VL_FUNRURAL'
        ,' CMP_VL_SERVICOS'
        ,' CMP_VL_IRRF'
        ,' CMP_RATEAR_FRETE_BC_ICMS'
        ,' CMP_RATEAR_FRETE_BC_ICMS_ST'
        ,' CMP_RATEAR_FRETE_BC_IPI'
        ,' CMP_RATEAR_FRETE_BC_PIS'
        ,' CMP_RATEAR_FRETE_BC_COFINS'
        ,' CMP_RATEAR_SEGURO_BC_ICMS'
        ,' CMP_RATEAR_SEGURO_BC_ICMS_ST'
        ,' CMP_RATEAR_SEGURO_BC_IPI'
        ,' CMP_RATEAR_SEGURO_BC_PIS'
        ,' CMP_RATEAR_SEGURO_BC_COFINS'
        ,' CMP_RATEAR_OUT_DESP_BC_ICMS'
        ,' CMP_RATEAR_OUT_DESP_BC_ICMS_ST'
        ,' CMP_RATEAR_OUT_DESP_BC_IPI'
        ,' CMP_RATEAR_OUT_DESP_BC_PIS'
        ,' CMP_RATEAR_OUT_DESP_BC_COFINS'
        ,' NFE_XML'
        ,' CMP_S_VL_TOTAL'
        ,' CMP_S_VL_BASE_CALC_ICMS'
        ,' CMP_S_VL_ICMS'
        ,' CMP_S_VL_BASE_CALC_ICMS_SUBST'
        ,' CMP_S_VL_ICMS_SUBST'
        ,' CMP_S_VL_IPI'
        ,' CMP_S_VL_PIS'
        ,' CMP_S_VL_COFINS'
        ,' CMP_TOTAL_SEM_DESCONTO'
        ,' CMP_S_BC_PIS'
        ,' CMP_S_BC_COFINS'
        ,' SCC_CODIGO'
        ,' ETL_CODIGO'
        ,' EGT_CODIGO'
        ,' NBC_CODIGO'
        ,' CMP_S_VL_COBRADO_NOME_TERCEIROS'
        ,' CMP_S_VL_TOTAL_CONSUMIDO'
        ,' CMP_S_CST_ICMS'
        ,' CMP_S_AL_ICMS'
        ,' CMP_S_AL_PIS'
        ,' CMP_S_AL_COFINS'
        ,' CMP_S_QTDE_CONSUMIDA'
        ,' STA_CODIGO'
        ,' ME_CODIGO'
        ,' PCC_CODIGO_ANALITICO'
        ,' EFC_CODIGO'
        ,' CMP_S_CST_PIS'
        ,' CMP_S_CST_COFINS'
        ,' CFOP_CODIGO_NF'
        ,' CFOP_CODIGO'
        ,' CMP_CTE_TIPO'
        ,' CMP_CTE_REFERENCIADO'
        ,' NFR_CODIGO'
        ,' DOC_NUMERO'
        ,' CMP_NFE_REGIME_ESPECIAL'
        ,' CMP_DT_COMPETENCIA'
        ,' PART_CODIGO'
        ,' CMP_XPED'
        ,' CMP_COD_MUN_ORIG'
        ,' CMP_COD_MUN_DEST'
        ,' PROJ_CODIGO'
        ,' CMP_APROVADA'
        ,' CMP_ICMS_FCPST_VALOR'
        ,' CMP_ICMS_FCPSTRET_VALOR'
        ,' CMP_VL_IPI_DEVOL'
        ,' NFE_FINNFE'
        ,' NOT_DATA_HORA_ALTER_SITUACAO'
    ];
}
