<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DAV extends Model
{
    use HasFactory;
    protected $connection;
    function __construct()
    {
        return $this->connection = env('APP_NAME');
    }
    protected $table = 'DAV';
    protected $primaryKey = 'DAV_NUMERO';
    public $timestamps = false;
    protected $fillable= [
        'DAV_NUMERO',
        ' DAV_NUMERO_AUXILIAR',
        ' DAV_TIPO',
        ' DAV_DATA',
        ' DAV_VALOR',
        ' DAV_CCF',
        ' DAV_ECF',
        ' DAV_ECF_NUMERO_SEQUENCIAL',
        ' DAV_COO',
        ' DAV_COO_IMPRESSAO',
        ' DAV_CCF_IMPRESSAO',
        ' DAV_ECF_IMPRESSAO',
        ' DAV_COO_RELATORIO',
        ' DAV_C_IMPRESSAO',
        ' DAV_CONTROLE',
        ' ENT_CODIGO',
        ' DAV_NOME_ADQUIRENTE',
        ' DAV_CPF_CNPJ_ADQUIRENTE',
        ' DAV_IE_RG_ADQUIRENTE',
        ' DAV_DATA_EMISSAO',
        ' DAV_DATA_CONFIRMACAO',
        ' DAV_DATA_FATURAMENTO',
        ' DAV_DATA_CANCELAMENTO',
        ' DAV_DATA_PREVISAO_VENDA',
        ' DAV_DATA_PREVISAO_ENTREGA',
        ' DAV_DATA_ENTREGA_REALIZADA',
        ' DAV_DATA_VALIDADE',
        ' DAV_DATA_IMPRESSAO',
        ' DAV_DATA_ENCERRAMENTO',
        ' DAV_DATA_ENTRADA',
        ' DAV_DATA_COMPETENCIA',
        ' DAV_VALOR_PRODUTOS',
        ' DAV_VALOR_FRETE',
        ' DAV_PERCENTUAL_DESCONTO',
        ' DAV_PERCENTUAL_DESCONTO_CONDPAG',
        ' DAV_VALOR_DESCONTO',
        ' DAV_VALOR_DESCONTO_CONDPAG',
        ' DAV_VALOR_TOTAL_DESCONTO',
        ' DAV_SITUACAO',
        ' DAV_SITUACAO_ENTREGA',
        ' CPA_CODIGO',
        ' DAV_OBSERVACOES',
        ' DAV_OBSERVACOES_EXTRAS',
        ' DOC_NUMERO',
        ' DAV_LICITACAO',
        ' FNE_CODIGO',
        ' USU_COD_CRIACAO',
        ' USU_COD_VENDEDOR',
        ' CON_TIPO_PAGAMENTO',
        ' DAV_PERCENTUAL_ENTREGA',
        ' DEP_CODIGO',
        ' DAV_SITUACAO_EXECUCAO',
        ' DAV_HORA_INCLUSAO',
        ' OSP_CODIGO',
        ' DAV_INSTALACAO',
        ' DAV_DEFEITO_INFORMADO_CLIENTE',
        ' DAV_DEFEITO_INFORMADO_TECNICO',
        ' DAV_RETRABALHO',
        ' DAV_GARANTIA',
        ' OSTA_CODIGO',
        ' FUN_CODIGO',
        ' EOB_CODIGO',
        ' DAV_KM',
        ' DAV_HORA_ENCERRAMENTO',
        ' DAV_EQUIPAMENTO_MODELO',
        ' DAV_EQUIPAMENTO_SERIE',
        ' DAV_GARANTIA_LOJA',
        ' DAV_GARANTIA_NOTA',
        ' DAV_GARANTIA_DATA',
        ' DAV_NUMERO_ORIGINAL',
        ' DAV_HORA_ENTRADA',
        ' DAV_FRETE_DESCRICAO',
        ' DAV_PRAZO_ENTREGA_DESCRICAO',
        ' DAV_IMPOSTO_DESCRICAO',
        ' PART_CODIGO_TRANSPORTADORA',
        ' DAV_TELEFONE',
        ' DAV_CELULAR',
        ' DAV_EMAIL',
        ' DAV_PESSOA_CONTATO',
        ' DAV_ENDERECO_LOGRADOURO',
        ' DAV_ENDERECO_NUMERO',
        ' DAV_ENDERECO_COMPLEMENTO',
        ' DAV_ENDERECO_BAIRRO',
        ' DAV_ENDERECO_CEP',
        ' MUN_CODIGO',
        ' DAV_VALOR_IPI',
        ' DMP_CODIGO',
        ' DAV_NUMERO_WEB',
        ' DAV_ORDEM_COMPRA',
        ' PART_CODIGO',
        ' CBA_CODIGO',
        ' DAV_DIA_UNICO_VENCIMENTO',
        ' PART_REPRESENTANTE_CODIGO',
        ' CBO_CAMPO_CUSTOMIZADO_SEQUENCIA',
        ' PART_INDICADOR_CODIGO',
        ' DSF_CODIGO',
        ' PROJ_CODIGO',
        ' DAV_VALOR_FECHADO',
        ' DAV_NOME_SOLICITANTE',
        ' PREENCHIMENTO_VISITA_MANUAL',
        ' PR_CONSIG_SITUACAO',
        ' DAV_FINALIZA_CONSIG',
        ' DAV_VALOR_TROCO',
        ' DAV_VALOR_COMISSAO',
        ' DAV_VALOR_ICMS_ST',
        ' DAV_DESCRICAO',
        ' DAV_PRONTA_ENTREGA',
        ' DAV_VALOR_ENTRADA_PARCELA',
        ' DAV_VALOR_TOTAL_SERVICOS',
        ' DAV_VALOR_TOTAL_PRODUTOS',
        ' DAV_VALOR_DESCONTO_SERVICOS',
        ' DAV_VALOR_DESCONTO_PRODUTOS',
        ' DAV_PERC_DESCONTO_PRODUTOS',
        ' DAV_PERC_DESCONTO_SERVICOS',
        ' TBPR_ID',
        ' TBPRV_ID',
        ' DAV_PERCENTUAL_ACRES_CONDPAG',
        ' DAV_VALOR_ACRES_CONDPAG',
        ' DAV_PED_ACUMULATIVO',
        ' DAV_POSSUI_VENDA_IMPULSO',
        ' DTE_CODIGO',
        ' DAV_DESC_MAX_LIBERACAO',
        ' DAV_DESC_MAX_LIBERACAO_OBS',
        ' DAV_DESC_MAX_APROVADO',
        ' DAV_DESC_MAX_APROVADO_DATA_HORA',
        ' DAV_DESC_MAX_APROVADO_USUARIO',
        ' DAV_DESC_MAX_APROVADO_OBS',
        ' DAV_OBSERVACOES_RESUMIDAS',
        ' CBO_CODIGO',
        ' DSP_CODIGO',
        ' DAV_SEG_CODIGO',
        ' DAV_LINK_RELATORIO_UMOV',
        ' DAV_OBS_ORC_UMOV_ME',
        ' DAV_VALOR_LIQUIDO',
        ' DAV_ACTIVITYHISTORY_ID',
        ' DAV_NUMERO_CRM',
        ' USU_COD_ULT_ATUALIZACAO',
        ' DATA_HORA_ULT_ATUALIZACAO',
        ' DATA_HORA_CRIACAO',
        ' DAV_NAO_GERAR_FINANCEIRO',
        ' DAV_REALIZADO_DESPACHO',
        ' NOT_DATA_HORA_ALTER_SITUACAO',
        ' DAV_CANCELAMENTO_INTEGRADO',
        ' DAV_KM_HR',
        ' DAV_CONTROLE_USUARIO'
	];

}
