<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DAV_ITENS extends Model
{
    use HasFactory;
    protected $connection;
    function __construct()
    {
        return $this->connection = env('APP_NAME');
    }
    protected $table = 'DAV_ITENS';
    protected $primaryKey = ['DAV_NUMERO', 'DAVI_ITEM'];
    public $timestamps = false;
    protected $fillable= [
        'DAV_NUMERO',
        ' DAVI_ITEM',
        ' DAV_TIPO',
        ' PRD_CODIGO',
        ' PRD_CODIGO_DIGITADO',
        ' DAVI_DESCRICAO',
        ' DAVI_UM',
        ' DAVI_QTDE',
        ' DAVI_QTDE_TROCA',
        ' DAVI_VL_UNIT',
        ' DAVI_PERC_DESCONTO',
        ' DAVI_VL_DESCONTO',
        ' DAVI_PERC_ACRESCIMO',
        ' DAVI_VL_ACRESCIMO',
        ' DAVI_VL_TOTAL_BRUTO',
        ' DAVI_VL_TOTAL',
        ' DAVI_DATA',
        ' DAVI_TOTALIZADOR',
        ' DAVI_CANCELADO',
        ' DAVI_CONTROLE',
        ' DAVI_CONTROLE_2',
        ' DAVI_SITUACAO_TRIBUTARIA',
        ' DAVI_ALIQUOTA',
        ' DAVI_QTDE_ENTREGA',
        ' DAVI_DATA_PREVISAO_ENTREGA',
        ' DAVI_DATA_ENTREGA_REALIZADA',
        ' DAVI_PERCENTUAL_ENTREGA',
        ' DAVI_RESERVA',
        ' DAVI_TIPO_OS',
        ' DAVI_QTDE_VOLUMES',
        ' DAVI_VL_UNIT_DIGITADO',
        ' DAVI_PERC_DESCONTO_DIGITADO',
        ' DAVI_VL_DESCONTO_DIGITADO',
        ' DAVI_PERC_ACRESCIMO_DIGITADO',
        ' DAVI_VL_ACRESCIMO_DIGITADO',
        ' DAVI_CASAS_DEC_QTDE',
        ' DAVI_CASAS_DEC_VALOR_UNITARIO',
        ' REG_CODIGO',
        ' REG_CODIGO_IPI',
        ' CST_IPI',
        ' COD_ENQ_LEG_IPI',
        ' DAVI_IPI_BC',
        ' DAVI_IPI_ALIQUOTA',
        ' DAVI_IPI_VALOR',
        ' DAVI_ICMS_CST',
        ' DAVI_ICMS_BC',
        ' DAVI_ICMS_ALIQUOTA',
        ' DAVI_ICMS_VALOR',
        ' DAVI_PIS_ALIQUOTA',
        ' DAVI_PIS_VALOR',
        ' DAVI_COFINS_ALIQUOTA',
        ' DAVI_COFINS_VALOR',
        ' PRO_CODIGO',
        ' PROI_ITEM',
        ' DAVI_QTDE_PRODUZIR',
        ' DMP_CODIGO',
        ' DAVI_FRETE_VALOR_UNITARIO',
        ' DAVI_FRETE_VALOR_TOTAL',
        ' DAVI_COMISSAO_ORIGEM',
        ' DAVI_COMISSAO_PERC',
        ' DAVI_ICMS_SN_ORIGEM',
        ' DAVI_ICMS_SN_CSOSN',
        ' DAVI_ICMS_SN_BC',
        ' DAVI_ICMS_SN_ALIQUOTA',
        ' DAVI_ICMS_SN_VALOR',
        ' DAVI_VL_UNIT_NEGOCIACAO',
        ' DAVI_VL_TOTAL_NEGOCIACAO',
        ' DAVI_SN_ALIQUOTA',
        ' DAVI_SN_VALOR',
        ' DAVI_CARACTERISTICA_01',
        ' DAVI_CARACTERISTICA_02',
        ' DAVI_CARACTERISTICA_03',
        ' DAVI_CARACTERISTICA_04',
        ' DAVI_CARACTERISTICA_05',
        ' DAVI_OBSERVACOES',
        ' DAVI_VALOR_ORCADO',
        ' DAVI_QTDE_RETORNADA',
        ' DAVI_CCD_CODIGO',
        ' DAVI_PROJ_CODIGO',
        ' DAVI_VL_CUSTO_CADASTRO',
        ' DAVI_VL_CUSTO_MEDIO_CADASTRO',
        ' DAVI_VL_AQUIS_DESP_CADASTRO',
        ' DAVI_PERC_COMISSAO',
        ' DAVI_VALOR_COMISSAO',
        ' DAVI_TOTAL_VL_UNIT_VL_COMISSAO',
        ' DAVI_ICMS_ST_BC',
        ' DAVI_ICMS_ST_ALIQUOTA',
        ' DAVI_ICMS_ST_VALOR',
        ' TAB_PRECO_BASE',
        ' TAB_PRECO_MIN',
        ' TAB_PRECO_MAX',
        ' DAVI_INFORMACOES_ADICIONAIS',
        ' DAVI_VENDA_IMPULSO',
        ' DAVI_ITEM_IMPULSO',
        ' DAVI_VOLUME_ITEM_UNIT',
        ' DAVI_VOLUME_ITEM_TOTAL',
        ' DTE_CODIGO',
        ' DAVI_DESC_MAX_EXCEDIDO',
        ' DAVI_NEGOCIACAO_MARKUP',
        ' DAVI_DESC_VL_UNIT',
        ' FPR_CODIGO',
        ' DAVI_SITUACAO_ITEM_OS',
        ' DAVI_QTDE_REQUISITAR',
        ' DAVI_QTDE_REQUISITADA_COMPRADA',
        ' DAVI_QTDE_REQUISITADA',
        ' DAVI_PESADO_REGISTRADO',
        ' DAVI_QTD_SOLICITADA',
        ' DAVI_QTD_PESADA',
        ' CBE_CODIGO',
        ' CBO_CODIGO',
        ' EOB_CODIGO',
        ' DAVI_OBS_ORCAMENTO',
        ' DAVI_DATA_ULT_ATT_CUSTO',
        ' DAVI_GESTAO_ENCERRADO',
        ' DAVI_CARACTERISTICA_06',
        ' DAVI_CARACTERISTICA_07',
        ' DAVI_CARACTERISTICA_08',
        ' DAVI_CARACTERISTICA_09',
        ' DAVI_CARACTERISTICA_10',
        ' DAVI_COMISSAO_MANUAL',
	];

}
